languageCode = "en"
languageName = "English"
weight = 1
title = "Frankline's Terminal Insights"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "/images/avatar.png"
  secondaryLogo = "static/images/avatar.png"
  description = "Practical cybersecurity writeups, forensic investigations, attack simulations, and hands-on security research with a focus on methodology, tools, and real-world application."
  copyright = "© 2026 FranklineOsec. All rights reserved."

[author]
  name = "FranklineO-sec"
  image = "/images/avatar.png"
  headline = "Cybersecurity Analyst | CTF Player"
  bio = "Exploring cybersecurity through CTFs, digital forensics, and practical security research."
  links = [
    { email = "franc.otieno22@gmail.com" },
    { link = "https://franklineo-sec.github.io/" },
    { github = "https://github.com/FranklineO-sec" },
    { linkedin = "https://www.linkedin.com/in/frankline-otieno" },
  ]
